### ISSUE TITLE
Please fix conflicting timeouts in your configs

### ISSUE THREAD

**Issue by wswebcreation** [WasiqB/my-wdio#1] opened 2020-01-25 15:55 UTC
Based on the issue you filled I checked the configs. Please see the comment in this issue and fix your conflicting timeouts https://github.com/wswebcreation/wdio-native-app-compare/issues/13#issuecomment-578417326. This will make the project even better to use for everybody.

Thanks for creating this awesome setup

**Comment by WasiqB** [comment] 2020-01-26 10:46
@wswebcreation , thanks for highlighting the issue, the issue is now fixed. Now there is no diff image being created even when there is difference in time on the notification status bar. Closing the ticket.

**Closed as completed by WasiqB** 2020-01-26 10:46 UTC
Labels: bug
